### ISSUE TITLE
[Debian] apt module has changed requirements

### ISSUE THREAD

**Issue by JonTheNiceGuy** [djjudas21/puppet-ossec#24]
I'm getting the following in my logs:

    Aug 18 05:33:33 vm puppet-master[1612]: (Scope(Apt::Source[alienvault])) $include_src is deprecated and will be removed in the next major release, please use $include => { 'src' => false } instead
    Aug 18 05:33:33 vm puppet-master[1612]: (Scope(Apt::Source[alienvault])) $include_deb is deprecated and will be removed in the next major release, please use $include => { 'deb' => true } instead
    Aug 18 05:33:33 vm puppet-master[1612]: (Scope(Apt::Source[alienvault])) $key_source is deprecated and will be removed in the next major release, please use $key => { 'source' => http://ossec.alienvault.com/repos/apt/conf/ossec-key.gpg.key } instead.
    Aug 18 05:33:33 vm puppet-master[1612]: (Scope(Apt::Key[Add key: 9A1B1C65 from Apt::Source alienvault])) $key_source is deprecated and will be removed in the next major release. Please use $source instead.

I'll try and get a PR in, but for now, here's an issue, and if someone else gets to it first, so much the better :)

**Comment by djjudas21** [comment]
Just to let you know this module is being deprecated as it is not actively maintained. There is a fork of this module called [`wazuh/ossec`](https://github.com/wazuh/ossec-puppet) which is under actively development.

You may find your issue has been fixed in that module, and if not, please open this issue against their repo.

Thanks,
Jonathan
