### ISSUE TITLE
Some way to have puppet not manage the server's client.keys file.

### ISSUE THREAD

**Issue by TravellingGuy** [djjudas21/puppet-ossec#34]
I had a weird problem where puppet decided to clear out my client.keys file on the OSSEC server.

Previously I had submitted the pull request (in client.pp) such that if $::uniqueid does not exist, run agent-auth on the agent instead of having the puppet module manage the agent key. So, I think my problem is an extension of that. In the end, if we are using agent-auth on the agent to register it with the server (with ossec-authd running on the OSSEC server), we don't want puppet to touch the client.keys file on the server at all.

Unfortunately, I'm not sure of the best way to do that. In server.pp, I'm guessing we would need some sort of check (class parameter the user can set maybe?) to determine whether the module should be managing the client.keys file on the server at all.

**Comment by sedlund** [comment]
I'm still having to comment out the $::uniqueid portion of this code to get my clients to auth to the master.

Would it be as simple as only running agent-auth if /var/ossec/etc/client.keys doesn't exist?

**Comment by djjudas21** [comment]
Just to let you know this module is being deprecated as it is not actively maintained. There is a fork of this module called [`wazuh/ossec`](https://github.com/wazuh/ossec-puppet) which is under actively development.

You may find your issue has been fixed in that module, and if not, please open this issue against their repo.

Thanks,
Jonathan
